export const equip_positions_by_name = {
  r_finger: 'Al dito destro',
  l_finger: 'Al dito sinistro',
  neck: 'Al collo',
  body: 'Sul corpo',
  head: 'In testa',
  legs: 'Sulle gambe',
  feet: 'Ai piedi',
  hands: 'Sulle mani',
  arms: 'Sulle braccia',
  around: 'Attorno al corpo',
  waist: 'In vita',
  r_wrist: 'Al polso destro',
  l_wrist: 'Al polso sinistro',
  r_hand: 'Nella mano destra',
  l_hand: 'Nella mano sinistra',
  back: 'Sulla schiena',
  r_ear: 'All\'orecchio destro',
  l_ear: 'All\'orecchio sinistro',
  eyes: 'Sugli occhi',
  sheath: 'Nel fodero',
  belt: 'Alla cintura',
  over: 'A tracolla',
  r_shoulder: 'Sulla spalla destra',
  l_shoulder: 'Sulla spalla sinistra',
  tied: 'Imprigionato'
};

